name: Sync Upstream Master

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 UTC 2:00，即北京时间 10:00
  workflow_dispatch:     # 手动触发也支持

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 我们会用 token 自己 push
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config user.name "xho22"
          git config user.email "stephenyyxx@gmail.com"

      - name: Add upstream remote
        run: git remote add upstream ${{ secrets.UPSTREAM_REPO }}

      - name: Fetch upstream
        run: git fetch upstream

      - name: Rebase master onto upstream/master
        run: |
          git checkout master
          git rebase upstream/master

      - name: Push changes to your fork
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} master --force
